### ISSUE TITLE
libvdwxc web page moved

### ISSUE THREAD

**Issue by askhl** [conda-forge/libvdwxc-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Hi @gdonval, libvdwxc moved to https://libvdwxc.materialsmodeling.org/ a few years ago.  The old domain (libvdwxc dot org) has expired but has since been bought by others who have set up a mock of the original website in order to promote a financial scam.

libvdwxc on conda-forge still links to the old web site (https://anaconda.org/conda-forge/libvdwxc).  Would you be able to update to the new website please?

Thanks!

### Installed packages

```shell
none
```

### Environment info

```shell
none
```

**Comment by askhl** [comment]
Also, now that I'm here, thanks a lot for your work on the conda package!

**Comment by gdonval** [comment]
That was nasty. It's fortunate it's some AI crap and the page wasn't rewritten to make people compile a corrupted version of the lib.

On your gitlab:

![Image](https://github.com/user-attachments/assets/1a471bd1-4b97-4936-a34d-ec22516b867b)

That bit under "project information" still points to the old website.

I've also added you as a maintainer here. I don't expect you to do anything special but should you wish to, now you can.

**Comment by askhl** [comment]
Thank you very much, and also for the quick fix, and for catching the leftover link which I have now fixed.  Very annoying this problem 💀
